### ISSUE TITLE
Getting run time error. Is there any way to change the settings?

### ISSUE THREAD

**Issue by ModiShrushti** [sneuensc/mapache#34]
picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 20.70 minutes.
Runtime.totalMemory()=1959788544
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:267)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:241)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:233)
	at java.util.ArrayList.add(ArrayList.java:464)
	at htsjdk.samtools.SAMUtils.getAlignmentBlocks(SAMUtils.java:743)
	at htsjdk.samtools.SAMRecord.getAlignmentBlocks(SAMRecord.java:1919)
	at htsjdk.samtools.SAMRecord.validateCigar(SAMRecord.java:1937)
	at htsjdk.samtools.BAMRecord.getCigar(BAMRecord.java:284)
	at htsjdk.samtools.SAMRecord.isValid(SAMRecord.java:2233)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:848)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:834)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:802)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:591)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:570)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:524)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)

**Comment by sneuensc** [comment]
Dear ModiShrushti,
I am not sure if you want to inform my about an issue or if you solved it already. Your task is running out of memory. So please allocate more memory using the following arguments in your config file:
```
remove_duplicates:
    mem: 32
```

**Comment by ModiShrushti** [comment]
I wanted to inform you about this error. As per your suggestion I changed modified the config file to mem:32. But still I am getting the same error. Could you please look into this?
This is the error I am getting:

_Runtime.totalMemory()=1995440128
_To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:141)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:558)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:257)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:308)
	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)__

**Comment by sneuensc** [comment]
Dear ModiShrushti,
Thank you for signaling it. I am happy to look into it. Would it be possible to share the config file with me as I am not able to reproduce the error with my data? For privacy reasons you can also send me the config file by mail (samuel.neuenschwander(at)unil.ch).
